name: discord_form_flutter
description: A simple, clean looking form that can save you time when creating a signup page for example.
             It is easy to use and also packed up with default style that is very similar to discord forms.
             Give it a try ✨
version: 0.0.1
homepage: https://github.com/AymanProjects/discord_form_flutter


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: